import type { FormSpec, FormType } from "./types";
import { FORM_TYPE_LABELS } from "./types";
import { formatMoneyCents } from "@/lib/money";

type TemplateGuardian = {
  relationship: string;
  firstName: string;
  lastName: string;
  idNumber: string | null;
  occupation: string | null;
  phone: string | null;
  email: string | null;
};

type TemplateChild = {
  firstName: string;
  lastName: string;
  dateOfBirth: Date | null;
  gender: "MALE" | "FEMALE" | "OTHER" | null;
  enrollmentDate: Date | null; // null = blank template (Forms page)
  parentName: string;
  parentPhone: string | null;
  parentEmail: string | null;
  childIdNumber: string | null;
  parentIdNumber: string | null;
  feeOverrideCents: number | null;
  photoConsentGiven: boolean;
  photoConsentAt: Date | null;
  category: { name: string; monthlyFeeCents: number | null };
};

type TemplateInput = {
  organizationName: string;
  currencyCode: string;
  child: TemplateChild;
  guardians: TemplateGuardian[];
};

function fmtDate(d: Date | null): string | null {
  if (!d) return null;
  return d.toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

const GENDER_LABEL: Record<string, string> = { MALE: "Male", FEMALE: "Female", OTHER: "Other" };

// Guardian sections: one section per guardian on file, plus a placeholder
// section inviting a blank one to be filled in by hand when the child has
// none on file yet -- Session 1's Guardian model may simply be empty for
// a child added before Session 1, or one where the school hasn't gotten
// around to it.
function guardianSections(guardians: TemplateGuardian[]) {
  if (guardians.length === 0) {
    return [
      {
        heading: "Parent / guardian",
        fields: [
          { label: "Full name", value: null },
          { label: "Relationship to child", value: null },
          { label: "ID number", value: null },
          { label: "Phone", value: null },
          { label: "Email", value: null },
        ],
      },
    ];
  }
  return guardians.map((g) => ({
    heading: `${g.relationship || "Guardian"}`,
    fields: [
      { label: "Full name", value: `${g.firstName} ${g.lastName}`.trim() || null },
      { label: "ID number", value: g.idNumber },
      { label: "Occupation", value: g.occupation },
      { label: "Phone", value: g.phone },
      { label: "Email", value: g.email },
    ],
  }));
}

const LEGAL_DISCLAIMER =
  "This is a fill-in-the-blank draft generated by Crechely, not reviewed legal wording. Have your own legal advisor review and adapt this document before relying on it.";

export function buildFormSpec(formType: FormType, input: TemplateInput): FormSpec {
  const { child, guardians, currencyCode } = input;
  const childSection = {
    heading: "Child",
    fields: [
      { label: "Full name", value: `${child.firstName} ${child.lastName}`.trim() || null },
      { label: "Date of birth", value: fmtDate(child.dateOfBirth) },
      { label: "Gender", value: child.gender ? GENDER_LABEL[child.gender] : null },
      { label: "Class", value: child.category.name || null },
      { label: "Enrolment date", value: fmtDate(child.enrollmentDate) },
      { label: "Child ID number", value: child.childIdNumber },
    ],
  };

  switch (formType) {
    case "ENROLMENT":
      return {
        title: FORM_TYPE_LABELS.ENROLMENT,
        intro:
          "Enrolment record for the child and guardian details below. Fields already on file are filled in; anything blank should be completed by hand.",
        sections: [childSection, ...guardianSections(guardians), {
          heading: "Home address",
          fields: [{ label: "Address", value: null }],
        }],
        signatureLine: true,
      };

    case "RE_REGISTRATION":
      return {
        title: FORM_TYPE_LABELS.RE_REGISTRATION,
        intro:
          "Please confirm the details below are still correct for the coming year, or note any changes on the blank lines provided.",
        sections: [
          childSection,
          ...guardianSections(guardians),
          {
            heading: "Changes since last registration",
            fields: [
              { label: "1", value: null },
              { label: "2", value: null },
              { label: "3", value: null },
            ],
          },
        ],
        signatureLine: true,
      };

    case "INDEMNITY":
      return {
        title: FORM_TYPE_LABELS.INDEMNITY,
        intro:
          "By signing below, the parent/guardian named acknowledges the activities, risks and terms set out by the school for this child's care.",
        sections: [
          childSection,
          {
            heading: "Parent / guardian",
            fields: [
              { label: "Full name", value: guardians[0] ? `${guardians[0].firstName} ${guardians[0].lastName}` : child.parentName || null },
              { label: "ID number", value: guardians[0]?.idNumber ?? child.parentIdNumber },
            ],
          },
          {
            heading: "Terms",
            fields: [
              { label: "1", value: null },
              { label: "2", value: null },
              { label: "3", value: null },
            ],
          },
        ],
        disclaimer: LEGAL_DISCLAIMER,
        signatureLine: true,
      };

    case "MEDICAL_ALLERGY":
      return {
        title: FORM_TYPE_LABELS.MEDICAL_ALLERGY,
        intro:
          "Medical and allergy information for staff caring for this child. Please complete every field that applies, and update whenever anything changes.",
        sections: [
          childSection,
          {
            heading: "Medical information",
            fields: [
              { label: "Known allergies", value: null },
              { label: "Chronic conditions", value: null },
              { label: "Current medication", value: null },
              { label: "Doctor's name", value: null },
              { label: "Doctor's phone", value: null },
              { label: "Medical aid / scheme", value: null },
              { label: "Medical aid number", value: null },
              { label: "Other notes", value: null },
            ],
          },
        ],
        disclaimer: LEGAL_DISCLAIMER,
        signatureLine: true,
      };

    case "PHOTO_MEDIA_CONSENT":
      return {
        title: FORM_TYPE_LABELS.PHOTO_MEDIA_CONSENT,
        intro:
          "Consent for this child's photo or likeness to be used by the school (e.g. in the app, on notice boards, in newsletters). Current status on file is shown below; sign to confirm or update it.",
        sections: [
          childSection,
          {
            heading: "Current status on file",
            fields: [
              { label: "Consent given", value: child.photoConsentGiven ? "Yes" : "No" },
              { label: "Consent date", value: fmtDate(child.photoConsentAt) },
            ],
          },
          {
            heading: "Confirm or update",
            fields: [{ label: "I consent / do not consent (circle one)", value: null }],
          },
        ],
        disclaimer: LEGAL_DISCLAIMER,
        signatureLine: true,
      };

    case "EMERGENCY_CONTACT_PICKUP":
      return {
        title: FORM_TYPE_LABELS.EMERGENCY_CONTACT_PICKUP,
        intro:
          "Who to contact in an emergency, and who is authorized to collect this child. Guardians already on file are listed first.",
        sections: [
          childSection,
          ...guardianSections(guardians),
          {
            heading: "Additional person authorized to collect",
            fields: [
              { label: "Full name", value: null },
              { label: "Relationship to child", value: null },
              { label: "Phone", value: null },
            ],
          },
          {
            heading: "Additional person authorized to collect",
            fields: [
              { label: "Full name", value: null },
              { label: "Relationship to child", value: null },
              { label: "Phone", value: null },
            ],
          },
        ],
        signatureLine: true,
      };

    case "FEE_AGREEMENT": {
      const feeCents = child.feeOverrideCents ?? child.category.monthlyFeeCents;
      const feeLabel =
        feeCents != null
          ? `${formatMoneyCents(feeCents, currencyCode)} / month${child.feeOverrideCents != null ? " (child-specific rate)" : ` (${child.category.name} standard rate)`}`
          : null;
      return {
        title: FORM_TYPE_LABELS.FEE_AGREEMENT,
        intro:
          "Fee agreement confirming the monthly rate and payment method for this child, per the school's current fee structure.",
        sections: [
          childSection,
          {
            heading: "Fee",
            fields: [
              { label: "Monthly fee", value: feeLabel },
              { label: "Payment day of month", value: null },
              { label: "Payment method", value: null },
            ],
          },
        ],
        disclaimer: LEGAL_DISCLAIMER,
        signatureLine: true,
      };
    }
  }
}
